# 2019-01-30 (cc) <paul4hough@gmail.com>
#
---
variables:
  GOIMG: $CI_REGISTRY/cca/docks/golang
  DOCK: $CI_REGISTRY/$CI_PROJECT_PATH
  GOCACHE: /tmp/go-cache

build:
  image: $GOIMG
  stage: build
  cache:
    paths:
      - agate
  artifacts:
    paths:
      - agate
  script:
    - rake build_static

release:
  image: $GOIMG
  stage: build
  only:
    - tags@cca-devel/agate/0.9
  cache:
    paths:
      - agate
  artifacts:
    paths:
      - opt/maul/doc-snarf
  script:
    - rake release

yamllint:
  image: $CI_REGISTRY/cca/docks/yamllint
  script:
    - rake yamllint

test:
  image: $GOIMG
  script:
    - go test -v -mod=vendor ./...

deploy:
  stage: deploy
  image: $CI_REGISTRY/registry/hub.docker.com/docker:18.05.0-ce
  only:
    - tags@cca/maul/agate
  script:
    - docker build -t $DOCK:$CI_COMMIT_TAG .
    - docker tag $DOCK:$CI_COMMIT_TAG $DOCK:latest
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $DOCK
