# 2018-12-26 (cc) <paul4hough@gmail.com>
#
---
groups:
  - name: procs
    rules:
      - alert: mock-logger-down
        expr: >-
          namedprocess_namegroup_num_procs{
            groupname="mock-logger"}
          == 0
        labels:
          ansible: mock-logger-restart
        annotations:
          description: "{{ $labels.groupname }} is down"

      - alert: mock-service-down
        expr: >-
          namedprocess_namegroup_num_procs{
            groupname="mock-service"}
          == 0
        labels:
          ansible: mock-service-fail
        annotations:
          description: "{{ $labels.groupname }} is down"
